spring:
  profiles:
    active: EN,dog  # dev/qa isn't provided as active profile. Hence, values from application.yml file is considered

demo:
  username: YmlUser
  password: YmlPassword
  url: YmlUrl

